config/routes.rb
Rails.application.routes.draw do
  ActiveAdmin.routes(self)

  devise_for :users

  root to: "pages#home" # main page

  get "users", to: "users#show"

  get "users/lists", to: "users#list_users"

  # routes for api
  namespace :api do
    namespace :v1 do
      resources :users, only: [:index]
    end
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :full_name, presence: true

  has_one_attached :photo

  def self.ransackable_attributes(auth_object = nil)
    %w[created_at email encrypted_password full_name id remember_created_at reset_password_sent_at reset_password_token role updated_at]
  end
end

app/controllers/api/v1/users_controller.rb
# frozen_string_literal: true
module Api
  module V1
    class UsersController < ApplicationController
      def index
        @users = User.all
        render json: @users
      end
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    if current_user.role == true
      stored_location_for(resource) || admin_dashboard_path
    else
      stored_location_for(resource) || users_path
    end
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:full_name, :role, :photo])
    devise_parameter_sanitizer.permit(:account_update, keys: [:full_name, :role, :photo])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, :only => "reply", :raise => false

  def home
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def show
  end

  def list_users
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Desafio Umanni Test </title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>

  </head>

  <body class="bg-black">
    <%= render "shared/flashes" %>
    <%= render "shared/navbar" %>

    <div class="bg-main">
        <%= yield %>
    </div>
    <%= render "shared/footer" %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="container">
  <div class="row p-4">

     <div class="text-white px-5">
        <div class="mr-2">
          <h1>Welcome to the<br><strong>Umanni Manage Users</strong></h1>
          <p>Change your way to manage your users!  </p>
        </div>
      </div>

      <div class="col-md-6 col-lg-4 wow fadeIn" data-wow-delay=".3s" style="visibility: visible; animation-delay: 0.3s; animation-name: fadeIn;">
          <div class="services-item bg-light">
              <div class="p-4 text-center services-content">
                  <div class="services-content-icon">
                      <i class="fas fa-user-secret fa-7x mb-4 text-primary"></i>
                      <h4 class="mb-3"> Login </h4>
                      <p class="mb-4">
                        Lorem ipsum dolor sit amet elit. Sed efficitur quis purus ut interdum. 
                        Aliquam dolor eget urna ultricies tincidunt.
                      </p>
                      <%= link_to "Login", new_user_session_path, class: 'btn btn-secondary text-white px-5 py-3 rounded-pill btn-lg' %>
                  </div>
              </div>
          </div>
      </div>

      <div class="col-md-6 col-lg-4 wow fadeIn" data-wow-delay=".5s" style="visibility: visible; animation-delay: 0.5s; animation-name: fadeIn;">
          <div class="services-item bg-light">
              <div class="p-4 text-center services-content">
                  <div class="services-content-icon">
                      <i class="fa fa-envelope-open fa-7x mb-4 text-primary"></i>
                      <h4 class="mb-3">Digital Marketing</h4>
                      <p class="mb-4">Lorem ipsum dolor sit amet elit. Sed efficitur quis purus ut interdum. Aliquam dolor eget urna ultricies tincidunt.</p>
                      <a href="" class="btn btn-secondary text-white px-5 py-3 rounded-pill">Read More</a>
                  </div>
              </div>
          </div>
      </div>

      <div class="col-md-6 col-lg-4 wow fadeIn" data-wow-delay=".7s" style="visibility: visible; animation-delay: 0.7s; animation-name: fadeIn;">
          <div class="services-item bg-light">
              <div class="p-4 text-center services-content">
                  <div class="services-content-icon">
                      <i class="fas fa-laptop fa-7x mb-4 text-primary"></i>
                      <h4 class="mb-3">Sign up</h4>
                      <p class="mb-4">Lorem ipsum dolor sit amet elit. Sed efficitur quis purus ut interdum. Aliquam dolor eget urna ultricies tincidunt.</p>
                      <%= link_to "Sign up", new_user_registration_path, class: 'btn btn-secondary text-white px-5 py-3 rounded-pill btn-lg' %>
                  </div>
              </div>
          </div>
      </div>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<footer id="footer" class="overflow-hidden bg-black">
  <div class="container p-2">
    <div class="row">
      <div class="footer-top-area">
        <div class="row d-flex flex-wrap justify-content-between">
          <div class="col-lg-2 col-sm-6 pb-3">
            <div class="footer-menu text-uppercase">
              <h5 class="widget-title pb-2 link-no-sub">
                Links
              </h5>
              <ul class="menu-list list-unstyled text-uppercase">
                <li class="menu-item pb-2">
                  <a href="#">Home</a>
                </li>
                <li class="menu-item pb-2">
                  <a href="#">About</a>
                </li>
                <li class="menu-item pb-2">
                  <a href="#">Shop</a>
                </li>
                <li class="menu-item pb-2">
                  <a href="#">Blogs</a>
                </li>
                <li class="menu-item pb-2">
                  <a href="#">Contact</a>
                </li>
              </ul>
            </div>
          </div>
          <div class="col-lg-3 col-sm-6 pb-3">
            <div class="footer-menu text-uppercase">
              <h5 class="widget-title pb-2 link-no-sub">Help &amp; Info</h5>
              <ul class="menu-list list-unstyled">
                <li class="menu-item pb-2">
                  <a href="#">Order</a>
                </li>
                <li class="menu-item pb-2">
                  <a href="#">Policies</a>
                </li>
                <li class="menu-item pb-2">
                  <a href="#">Shipping + Delivery</a>
                </li>
                <li class="menu-item pb-2">
                  <a href="#">Contact Us</a>
                </li>
              </ul>
            </div>
          </div>
          <div class="col-lg-3 col-sm-6 pb-3">
            <div class="footer-menu contact-item">
              <h5 class="widget-title text-uppercase pb-2 link-no-sub">Contact Us</h5>
              <p class="text-white">
              Do you have any queries or suggestions?
                <a class="area-no-sub" href="mailto:">
                  yourinfo@gmail.com
                </a>
              </p>
              <p class="text-white" >
                If you need support? Just give us a call. 
                <a class="area-no-sub" href="">
                +55 111 222 333 44
                </a>
              </p>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
<hr>
</footer>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container">
    <a class="navbar-brand" href="#">
      LOGO
    </a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarText">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <%= link_to "Home", root_path , class: "nav-link active" %>
        </li>
        <li class="nav-item">
          <%= link_to "List User / React", users_lists_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">About</a>
        </li>
      </ul>
      <div class="navbar-text ms-auto">
        <% if user_signed_in? %>
        <li class="nav-item dropdown">
            <% if current_user.photo.attached? %>
              <%= image_tag current_user.photo, class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <% else %>
              <%= image_tag("/assets/default_profile.jpg", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false) %>
            <% end %>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
            <% if current_user.role? %>
            <li>
              <%= link_to "Profile", users_path, class: "dropdown-item my-0 text-black" %>
            </li>
            <li>
              <%= link_to "Dashboard", admin_root_path , class: "dropdown-item my-0 text-black" %>
            </li>
            <li>
             <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item my-0 text-black" %>
            </li>
            <% else %>
             <li>
              <%= link_to "Profile", users_path, class: "dropdown-item my-0 text-black" %>
            </li>
            <li>
              <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item my-0 text-black" %>
            </li>
             <% end %>
          </ul>
        </li>
        <% else %>
          <li class="nav-item ms-auto">
            <%= link_to "Login", new_user_session_path, class: "nav-link text-center my-0 text-light" %>
          </li>
        <% end %>
      </div>
    </div>
  </div>
</nav>

app/views/users/list_users.erb
<div class="box-login">
  <div class="card-login">
    <div class="container p-0">
      <div class="col-lg-12 text-light">
        <div class="card-body">
          <div class="card-title p-2">
            <h2>
              Lista de Usuários
            </h2>
          </div>

          <table class="table table-dark table-hover" data-controller="user">
            <thead>
            <tr>
              <th>Nome</th>
              <th>Email</th>
              <!-- Adicione mais colunas conforme necessário -->
            </tr>
            </thead>
            <tbody data-user-target="usersList">
            <!-- Os usuários serão carregados aqui -->
            </tbody>
          </table>


        </div>
      </div>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="box-login">
  <div class="card-login">

    <div class="container p-0">
      <div class="row">
        <div class="col p-0">
          <nav aria-label="breadcrumb" class="m-3">
            <ol class="breadcrumb">
              <li><%= link_to "Home", root_path, class: "text-light" %></li>
              <li class="breadcrumb-item text-light active" aria-current="page"></li>
              <li class="breadcrumb-item text-light active" aria-current="page">
                User Profile
              </li>
            </ol>
          </nav>
        </div>
      </div>

      <div class="p-0">

        <div class="col-lg-12">
          <div class="card-bg p-3">
            <div class="row">
               <div class="card-bg text-center p-2">
                <% if current_user.photo.attached? %>
                  <%= image_tag current_user.photo, class: "avatar-edit m-2", crop: :fill %>
                <% else %>
                  <%= image_tag("/assets/default_profile.jpg", class: "avatar-edit m-2") %>
                <% end %>
              </div>
            </div>

            <hr class="text-light m-2">

            <div class="row">
              <p class="text-light my-0 mx-2 py-2">Full name: <%= current_user.full_name %></p>
            </div>

            <hr class="text-light m-2">

            <div class="row">
              <p class="text-light my-0 mx-2 py-2">Email: <%= current_user.email %></p>
            </div>

            <hr class="text-light m-2">

            <div class="row">
              <p class="text-light my-0 mx-2 py-2">Role:
                <% if current_user.role? %>
                  <%= "Administrator" %>
                <% else %>
                  <%= "User" %>
                <% end %>
              </p>
            </div>

          </div>
        </div>

      </div>

      <div class="d-grid gap-4 col-12 mt-1">
        <%= link_to "Edit Profile", edit_user_registration_path, class: 'btn bg-primary text-white py-3 px-5' %>
        <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "btn bg-primary text-white py-3 px-5" %>
      </div>

    </div>

  </div>
</div>